PUT http://localhost:3001/api/blogs/5f2054fabbf8b516547599b0
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbG1lbnR4aGVsaWxpIiwiaWQiOiI1ZjIwNTQ4M2JiZjhiNTE2NTQ3NTk5YWYiLCJpYXQiOjE2MDY1MTY5ODV9.VrLMe9_eMHF4gRLZZFLU10_vNKsIsE3fFapl3vxCc7I

{
   "title": "udpated by kelment xhelili#11122",
   "author": "kelmend",
   "likes": 7,
   "url": "wwww.google.com"
}





