POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbG1lbnR4aGVsaWxpIiwiaWQiOiI1ZjE5NTk1MjZmMTYwYTI4MDQzNmM1ZmEiLCJpYXQiOjE1OTU1MDQ5Nzh9.1dLpzC-ECL1Fz6yd9amkosK7U2vhV-ATBoHieVj335Q

{
    "title": "kelmentxhelili middleware token tested",
    "author": "kelment",
    "url": "no url",
    "likes": 1
}


